### ISSUE TITLE
Arxlive pipeline failure

### ISSUE THREAD

**Issue by bishax** [nestauk/nesta#210]
Due to a deprecation in the MAG API (see below), the arxlive pipeline fails in `packages/mag/query_mag_api.py`:

```
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/luigi/worker.py", line 139, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/ec2-user/nesta/nesta/core/routines/arxiv/arxiv_mag_task.py", line 186, in run
    update_field_of_study_ids(mag_subscription_key, session, missing_fos_ids)
  File "/home/ec2-user/nesta/nesta/packages/mag/query_mag_api.py", line 201, in update_field_of_study_ids
    in query_fields_of_study(mag_subscription_key, ids=fos_ids)]
  File "/home/ec2-user/nesta/nesta/packages/mag/query_mag_api.py", line 200, in <listcomp>
    new_fos_to_import = [FieldOfStudy(**fos) for fos
  File "/home/ec2-user/nesta/nesta/packages/mag/query_mag_api.py", line 152, in query_fields_of_study
    del row[f]
KeyError: 'E'
ERROR:luigi-interface:[pid 19127] Worker Worker(salt=568461402, workers=10, host=ip-172-31-31-235, username=ec2-user, pid=19099, sudo_user=alex) failed    QueryMagTask(date=2020-01-15, _routine_id=2020-01-15-False, test=True, db_config_env=MYSQLDB, db_config_path=mysqldb.config, mag_config_path=mag.config, insert_batch_size=500, articles_from_date=None)
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/luigi/worker.py", line 139, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/ec2-user/nesta/nesta/core/routines/arxiv/arxiv_mag_task.py", line 186, in run
    update_field_of_study_ids(mag_subscription_key, session, missing_fos_ids)
  File "/home/ec2-user/nesta/nesta/packages/mag/query_mag_api.py", line 201, in update_field_of_study_ids
    in query_fields_of_study(mag_subscription_key, ids=fos_ids)]
  File "/home/ec2-user/nesta/nesta/packages/mag/query_mag_api.py", line 200, in <listcomp>
    new_fos_to_import = [FieldOfStudy(**fos) for fos
  File "/home/ec2-user/nesta/nesta/packages/mag/query_mag_api.py", line 152, in query_fields_of_study
    del row[f]
KeyError: 'E'
```

https://docs.microsoft.com/en-us/azure/cognitive-services/academic-knowledge/paperentityattributes

![image](https://user-images.githubusercontent.com/15673462/72425434-b8dbac80-377f-11ea-9fff-10ab2cd1e824.png)

**Comment by bishax** [comment]
MAG task now passes but path resolution fails:
```
>>> from nesta.core.luigihacks.misctools import find_filepath_from_pathstub as f3p
>>> f3p('batchables/arxiv/arxiv_elasticsearch')
'/home/ec2-user/nesta/docs/_build/html/_modules/nesta/core/batchables/arxiv/arxiv_elasticsearch'
>>> 
```
