### ISSUE TITLE
`nuts_finder` fails to install on AWS batch

### ISSUE THREAD

**Issue by bishax** [nestauk/nesta#213]
Example output from:

https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logEventViewer:group=/aws/batch/job;stream=py36_amzn1_image/default/89e2830f-a950-480b-8a82-a2078d4b6fc8

```
Collecting nuts_finder==0.1.5 (from -r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/ce/e1/40d5701e0a8b2b485c7d311d79f617470a74d9980d1040e7b0355ae9ea2d/nuts_finder-0.1.5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/py36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k_qwxxc6/nuts-finder/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k_qwxxc6/nuts-finder/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-k_qwxxc6/nuts-finder/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k_qwxxc6/nuts-finder/setup.py", line 9, in <module>
        long_description=open('README.md').read(),
      File "/opt/conda/envs/py36/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2902: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Error appears to be due to python using ascii decoding, despite the fact that `PYTHONIOENCODING` is set to `utf8` (https://github.com/nestauk/nesta/blob/150660496331236c2defecb878e301d658ec2f31/nesta/core/scripts/docker_recipes/py36_amzn1_image/Dockerfile#L8).

**Comment by bishax** [comment]
Potential fix is to add `ENV LANG en_US.UTF-8` to dockerfile c.f. https://grahamc.com/blog/ascii-decode-error-pip-install-docker
